name: perla-telemetry-stack
services:

  watchtower:
    image: containrrr/watchtower
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_POLL_INTERVAL=21600
      - DOCKER_API_VERSION=1.54
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped

  mosquitto:
    image: eclipse-mosquitto:2
    container_name: mosquitto
    restart: unless-stopped
    ports:
      - "1883:1883"
    volumes:
      - ./config:/mosquitto/config
      - ./mq-data:/mosquitto/data
      - ./mq-log:/mosquitto/log

  victoriametrics:
    image: victoriametrics/victoria-metrics:latest
    container_name: victoriametrics
    restart: unless-stopped
    ports:
      - "8428:8428"
    command:
      - "-storageDataPath=/victoria-metrics-data"
      - "-retentionPeriod=100y"
    volumes:
      - ./vm-data:/victoria-metrics-data

  telegraf:
    image: telegraf:latest
    container_name: telegraf
    restart: unless-stopped
    depends_on:
      - mosquitto
      - victoriametrics
    volumes:
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - ./telegraf/can_decode.star:/etc/telegraf/can_decode.star:ro